language: node_js
node_js:
  - "4.1"
branches:
  only:
    - master
script:
  - "npm run bower"
  - "npm run sprite"
  - "npm run build"
cache:
  directories:
    - bower_components
    - node_modules
after_success:
  - git config --global user.name "TRAVIS"
  - git config --global user.email "hello@internets.co.jp"
  - git add .
  - git commit -m "Add dist"
  - git push -qf https://$API_KEY@github.com/internets-inc/small-web.git gh-pages > /dev/null 2>&1
notifications:
  email:
    - hello@internets.co.jp
