language: node_js
node_js:
  - '4.1'
branches:
  only:
    - master
script:
  - npm run bower
  - npm run sprite
  - npm run build
cache:
  directories:
    - bower_components
    - node_modules
after_success:
  - rm .gitignore && cp gh-pages.ignore .gitignore
  - git config user.name "TRAVIS"
  - git config user.email "hello@internets.co.jp"
  - git add -A
  - git commit -m "Add dist"
  - '[$GH_TOKEN] && git push -qf https://$GH_TOKEN@github.com/internets-inc/small-web.git master:gh-pages > /dev/null 2>&1'
notifications:
  email:
    - hello@internets.co.jp
env:
  global:
    - secure: O+LXR5mN1meddJQn3zKto8nel/mA6d8IIcAvzl50ca64hSxwyWndmmSg7m2aAzrfdxMpxGTJWiV/0ADEMJAsFOWSjvHpcLzW5EqVXXbpKFjurtodSCmt+gz37N8ljj0npGawxe4p2S9e2ENJiyrVhOB5dqLDC+rvmP1tag82Qtaz3T8JMG3AYiyoRDyPL7oRlmcHqg58Ekt9lGhoWsbBHODXf6+Hu4VEKqrU969Sq20zPX2Ab704uQLA9ebQjUhYr7s93td6cSLWH2RooNYhWqoNaEYl306R4u1qToqQqqG0BRvhtCOmAXIV49ie82n87Ma50vDCTKOu+Rcl0UNqF/TvJuu9x6qfJN++Ja+afPtoKjdoT03iOayzhYaD1W7YDUgQ7c5GclmuFywxluEpXjaQnlMjXoZ4SZHLlLxBCpR5HtL0OK4kOirE/ItYxMUyoVAXjwtstDx9Mz7c2kq/4fquHj2oluAlOUTAfRU5na79SpbJI9oOFNvGDuzBaEoBR7lE8VjXwNKc6eC42aj9tqZDjXxXbIEinHjot0yBrgZPUXcoBEaKR3Yz0ayYboxvSPvK+o5zkji084OhcpGDVgUiub/JoTG9lSMhbHoRrR6Km4vgB1+LU/fnqj+zKpA12JXaYKXB7DzWFZmaCkBhbuHQiJagUVoYGs3pJxDOp0M=
