language: node_js
node_js:
  - '4.1'
branches:
  only:
    - master
script:
  - npm run bower
  - npm run sprite
  - npm run build
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_ade2291dba2d_key -iv $encrypted_ade2291dba2d_iv -in deploy_key.enc -out deploy.key -d
  - cp deploy.key ~/.ssh/
  - chmod 600 ~/.ssh/deploy.key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
  - ssh -T git@github.com
after_success:
  - rm .gitignore && cp gh-pages.ignore .gitignore
  - git config user.name "TRAVIS"
  - git config user.email "hello@internets.co.jp"
  - git add -A
  - git commit -m "Add dist"
  - git remote set-url origin git@github.com:internets-inc/small-web.git
  - git remote -v
  - git push -qf origin master:gh-pages
notifications:
  email:
    - hello@internets.co.jp
