language: node_js
node_js:
  - '4.1'
branches:
  only:
    - master
script:
  - npm run bower
  - npm run sprite
  - npm run build
cache:
  directories:
    - bower_components
    - node_modules
after_success:
  - rm .gitignore && cp gh-pages.ignore .gitignore
  - git config user.name "TRAVIS"
  - git config user.email "hello@internets.co.jp"
  - git remote set-url origin "https://${GH_TOKEN}@github.com/internets-inc/small-web.git"
  - git add -A
  - git commit -m "Add dist"
  - git push -qf origin master:gh-pages > /dev/null 2>&1
notifications:
  email:
    - hello@internets.co.jp
env:
  global:
    - secure: "SBrhcilsrwHk6oKeBywB5vH9sUy4B/xaIQRquEzdB8bW7t1VSt1VPG1+42+Apf+ZRPcto2i9BwxDVYHhfwzlbB/v85r14IEbG+8H5NGPuHwXhPw/pnZp1gkgPDqB3ZVytuaYOM4yYvHKqBk94AF35enCBJqP1rVydrCy/p1zgbjcG8CfjYmBYJxqOoGgNxs4k+FjxEnCkDQOwjcxRueqgAnxGKX/bS9ctxBctnhhVf9mF7BW9oxWo0MVIL2Yzg+Q9aZmPRmWgxxTofmI35aB2hMyN0RYLkfxiGGh4EBzK+YEFzcwudj2WOsZ4Ud+r+yB4UXkbxC56XKe8G7HJhIrijucejRpVafzNAGA98Y8LX3/mkr6ZW+c2+ntf0V12Dd1lhZlFZaEQKa11Gh4U0TsYCW5jp4tIMEwb3y6o28eo58xtcRZkZxN9S91m5HA/svowWwRp9yusHRFWlJJuTYATVeaYx+yWiIqREE62MpxGuPRgFLOp6Vxjoyd39CGJkbxMpbMoKmJzOunsB1Y7/tTig7aDbBDPquk+m/ft/fdcAXzhUZP1r8ucdUw16zKhNQLaxa33O6JwjNMsE/RJbQCbXumRBZZNlCakhwfn3atISQk9vDXoCPoMIQ49kBrQzoO8VA/EEsj322J7gRa6OGUAuC+VV0LyqslyF81PgBXY3k="
