language: node_js
node_js:
  - '4.1'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm run travis
before_install:
  - openssl aes-256-cbc -K $encrypted_ade2291dba2d_key -iv $encrypted_ade2291dba2d_iv -in deploy_key.enc -out deploy.key -d
  - cp deploy.key ~/.ssh/
  - chmod 600 ~/.ssh/deploy.key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
  - rm .gitignore && cp deploy_git.ignore .gitignore
after_success:
  - git --version
  - git config user.name "TRAVIS"
  - git config user.email "hello@internets.co.jp"
  - git remote set-url origin git@github.com:internets-inc/small-web.git
  - git checkout -b gh-pages
  - git status
  - git add -A
  - git commit -m "Add dist"
  - git push -f origin gh-pages
notifications:
  email:
    - hello@internets.co.jp
